"""ajoute le domaine de statut logement

Revision ID: 243c2f092c7b
Revises: 5b62294f6958
Create Date: 2026-08-25 11:24:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "243c2f092c7b"
down_revision: str | Sequence[str] | None = "5b62294f6958"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

STATUTS = ("Disponible", "En_maintenance", "Hors_service")


def _domaine() -> sa.Enum:
    return sa.Enum(
        *STATUTS,
        name="statut_logement",
        native_enum=False,
        create_constraint=True,
    )


def upgrade() -> None:
    """Upgrade schema."""
    # Le passage a `Enum(create_constraint=True)` pose le CHECK du domaine :
    # `alter_column` le genere, contrairement a une `CheckConstraint` ecrite a
    # la main. Meme mecanique qu'aux migrations 9e110ea805b4 (COMMANDE),
    # 32e3e8bc2f4e (LIVRAISON), 7d77916d25f0 (SESSION_FORMATION) et
    # fdc25d096467 (RESERVATION). Verifie apres coup dans `pg_constraint`.
    #
    # Aucune valeur « Occupe » dans le domaine, et c'est delibere : l'occupation
    # a une date donnee se deduit des RESERVATION actives sur cette periode.
    # Voir `docs/mld.md`.
    #
    # Echouerait sur une base contenant deja un logement hors domaine. Aucun
    # n'existe : LOGEMENT n'avait ni service ni router avant cette migration.
    #
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "logement",
        "statut",
        existing_type=sa.VARCHAR(length=30),
        type_=_domaine(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "logement",
        "statut",
        existing_type=_domaine(),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
