"""ajoute supplement_personnalisation a produit

Revision ID: 22127cdc2dce
Revises: e834cab7a5ad
Create Date: 2026-08-05 10:11:20.874829

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "22127cdc2dce"
down_revision: str | Sequence[str] | None = "e834cab7a5ad"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "produit",
        sa.Column(
            "supplement_personnalisation",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###

    # AJOUT MANUEL — l'autogeneration ne compare pas les contraintes CHECK, et
    # le comparateur introduit par Alembic 1.19 est desactive dans `env.py`
    # (faux positifs sur les `sa.Enum`). Cette contrainte n'apparait donc pas
    # dans le diff genere : elle est ecrite ici a la main, comme
    # `ck_commande_client_ou_invite` l'a ete au sprint 2.
    #
    # Elle echouerait sur une base contenant deja un produit personnalisable
    # sans tarif. Verifie au moment d'ecrire la migration : aucun n'existe. Si
    # le cas se presentait, l'echec serait le bon comportement — il faudrait
    # fixer un tarif, pas en inventer un ici, sous peine de rendre
    # silencieusement gratuite une personnalisation facturable.
    op.create_check_constraint(
        "personnalisable_a_un_supplement",
        "produit",
        "NOT est_personnalisable OR supplement_personnalisation IS NOT NULL",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Symetrique de l'ajout manuel : la contrainte tombe avant la colonne dont
    # elle depend.
    #
    # Le nom passe ici est **nu**, sans prefixe : la convention de nommage de
    # `core/database.py` le complete en `ck_produit_...`. Passer le nom complet
    # produirait `ck_produit_ck_produit_...` et un echec au downgrade — attrape
    # par l'aller-retour, pas par l'upgrade seul.
    op.drop_constraint("personnalisable_a_un_supplement", "produit", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("produit", "supplement_personnalisation")
    # ### end Alembic commands ###
