"""ajoute mot_de_passe nullable a personnel

Revision ID: e834cab7a5ad
Revises: 728322ff227b
Create Date: 2026-08-04 17:19:44.641877

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e834cab7a5ad"
down_revision: str | Sequence[str] | None = "728322ff227b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Nullable, et c'est le point : certaines fonctions n'ont structurellement
    # pas besoin d'un compte de connexion. `NULL` signifie « pas de compte » et
    # non « mot de passe vide » — `get_current_personnel` (#23) refusera
    # l'authentification dans ce cas, avec le meme message uniforme que les
    # autres refus.
    #
    # 255 caracteres : une empreinte bcrypt en fait 60, la marge couvre un
    # changement d'algorithme sans nouvelle migration. C'est la meme longueur
    # que `CLIENT.mot_de_passe`.
    #
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "personnel", sa.Column("mot_de_passe", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("personnel", "mot_de_passe")
    # ### end Alembic commands ###
