"""ajoute reference_publique et le CHECK client ou invite

Revision ID: 2befac0654c1
Revises: 9e110ea805b4
Create Date: 2026-07-28 14:15:04.733880

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2befac0654c1"
down_revision: str | Sequence[str] | None = "9e110ea805b4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("commande", sa.Column("reference_publique", sa.Uuid(), nullable=True))
    op.create_unique_constraint(
        op.f("uq_commande_reference_publique"), "commande", ["reference_publique"]
    )
    # ### end Alembic commands ###

    # AJOUT MANUEL — l'autogeneration d'Alembic ne compare pas les contraintes
    # CHECK : celle-ci n'apparaissait pas dans le diff genere, alors qu'elle est
    # bien declaree sur le modele. Contrainte n°5 du MLD.
    #
    # Elle echouerait sur une base contenant deja des commandes ne la respectant
    # pas. Aucune n'existe : la table est vide, et le service n'a jamais pu en
    # creer d'invalide puisqu'il renseigne toujours `id_client`.
    op.create_check_constraint(
        "client_ou_invite",
        "commande",
        "(id_client IS NOT NULL) <> (nom_invite IS NOT NULL)",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Ajout manuel symetrique de celui de `upgrade`.
    op.drop_constraint(op.f("ck_commande_client_ou_invite"), "commande", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_commande_reference_publique"), "commande", type_="unique"
    )
    op.drop_column("commande", "reference_publique")
    # ### end Alembic commands ###
