"""ajoute date_commande a commande

Revision ID: 263bf13e295b
Revises: 2befac0654c1
Create Date: 2026-07-29 16:22:00.314943

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "263bf13e295b"
down_revision: str | Sequence[str] | None = "2befac0654c1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # `NOT NULL` sans etape intermediaire : le `server_default` fournit une
    # valeur aux lignes deja presentes, PostgreSQL n'a donc rien a refuser.
    #
    # Consequence assumee : les commandes anterieures a cette migration sont
    # toutes horodatees a l'instant de son execution, et non a leur date reelle
    # de passation — celle-ci n'a jamais ete enregistree nulle part, elle est
    # irrecuperable. Elles resteront donc groupees en tete de l'historique. La
    # base de developpement etant seule concernee a ce stade, aucun script de
    # reprise n'est prevu.
    #
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "commande",
        sa.Column(
            "date_commande",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("commande", "date_commande")
    # ### end Alembic commands ###
