"""ajoute le domaine de statut reservation

Revision ID: fdc25d096467
Revises: 7d77916d25f0
Create Date: 2026-08-22 17:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fdc25d096467"
down_revision: str | Sequence[str] | None = "7d77916d25f0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

STATUTS = ("En_attente", "Confirmee", "Honoree", "Annulee")


def _domaine() -> sa.Enum:
    return sa.Enum(
        *STATUTS,
        name="statut_reservation",
        native_enum=False,
        create_constraint=True,
    )


def upgrade() -> None:
    """Upgrade schema."""
    # Le passage a `Enum(create_constraint=True)` pose le CHECK du domaine :
    # `alter_column` le genere, contrairement a une `CheckConstraint` ecrite a
    # la main. Meme mecanique qu'aux migrations 9e110ea805b4 (COMMANDE),
    # 32e3e8bc2f4e (LIVRAISON) et 7d77916d25f0 (SESSION_FORMATION). Verifie
    # apres coup dans `pg_constraint`.
    #
    # Echouerait sur une base contenant deja une reservation hors domaine.
    # Aucune n'existe : RESERVATION n'avait ni service ni router avant cette
    # migration, aucune ligne n'a pu etre creee par l'API.
    #
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "reservation",
        "statut",
        existing_type=sa.VARCHAR(length=30),
        type_=_domaine(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "reservation",
        "statut",
        existing_type=_domaine(),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
