"""ajoute adresse_livraison et le domaine de statut livraison

Revision ID: 32e3e8bc2f4e
Revises: 22127cdc2dce
Create Date: 2026-08-05 10:28:54.701846

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32e3e8bc2f4e"
down_revision: str | Sequence[str] | None = "22127cdc2dce"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

STATUTS = ("En_attente", "En_cours", "Livree", "Echouee", "Annulee")


def _domaine() -> sa.Enum:
    return sa.Enum(
        *STATUTS,
        name="statut_livraison",
        native_enum=False,
        create_constraint=True,
    )


def upgrade() -> None:
    """Upgrade schema."""
    # `date_heure_prevue` devient nullable : la livraison naît avec la commande,
    # aucune tournee n'est planifiee a cet instant. La garder NOT NULL forcerait
    # a inventer une date — « dans deux heures » — c'est-a-dire a ecrire une
    # promesse que rien ne garantit. NULL signifie « pas encore planifiee »,
    # comme `id_personnel` signifie « pas encore affectee ».
    #
    # Le passage a `Enum(create_constraint=True)` pose le CHECK du domaine :
    # contrairement a `CheckConstraint` ecrite a la main, `alter_column` le
    # genere ici — meme mecanique qu'a la migration 9e110ea805b4 pour
    # `COMMANDE.type_commande` et `COMMANDE.statut`. Verifie apres coup en
    # interrogeant `pg_constraint`.
    #
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("commande", sa.Column("adresse_livraison", sa.Text(), nullable=True))
    op.alter_column(
        "livraison",
        "date_heure_prevue",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "livraison",
        "statut",
        existing_type=sa.VARCHAR(length=30),
        type_=_domaine(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Le retour a NOT NULL sur `date_heure_prevue` echouerait si une livraison
    # non planifiee existe — ce qui est le cas nominal apres cette migration.
    # C'est assume : le downgrade sert a defaire une migration fraiche, pas a
    # revenir en arriere sur des donnees produites depuis.
    #
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "livraison",
        "statut",
        existing_type=_domaine(),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    op.alter_column(
        "livraison",
        "date_heure_prevue",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.drop_column("commande", "adresse_livraison")
    # ### end Alembic commands ###
