"""ajoute le domaine de statut session formation

Revision ID: 7d77916d25f0
Revises: 32e3e8bc2f4e
Create Date: 2026-08-22 16:20:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d77916d25f0"
down_revision: str | Sequence[str] | None = "32e3e8bc2f4e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

STATUTS = ("Planifiee", "Ouverte", "Terminee", "Annulee")


def _domaine() -> sa.Enum:
    return sa.Enum(
        *STATUTS,
        name="statut_session_formation",
        native_enum=False,
        create_constraint=True,
    )


def upgrade() -> None:
    """Upgrade schema."""
    # Le passage a `Enum(create_constraint=True)` pose le CHECK du domaine :
    # `alter_column` le genere, contrairement a une `CheckConstraint` ecrite a
    # la main. Meme mecanique qu'aux migrations 9e110ea805b4 (COMMANDE) et
    # 32e3e8bc2f4e (LIVRAISON). Verifie apres coup dans `pg_constraint`.
    #
    # Echouerait sur une base contenant deja une session hors domaine. Aucune
    # n'existe : SESSION_FORMATION n'avait ni service ni router avant cette
    # migration, aucune ligne n'a pu etre creee.
    #
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "session_formation",
        "statut",
        existing_type=sa.VARCHAR(length=30),
        type_=_domaine(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "session_formation",
        "statut",
        existing_type=_domaine(),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
