"""schema initial des 20 tables du MLD

Revision ID: a0513a08ec73
Revises:
Create Date: 2026-07-27 10:19:19.175445

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a0513a08ec73"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categorie_produit",
        sa.Column("id_categorie", sa.Integer(), nullable=False),
        sa.Column("libelle", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id_categorie", name=op.f("pk_categorie_produit")),
        sa.UniqueConstraint("libelle", name=op.f("uq_categorie_produit_libelle")),
    )
    op.create_table(
        "client",
        sa.Column("id_client", sa.Integer(), nullable=False),
        sa.Column(
            "type_client",
            sa.Enum(
                "Particulier",
                "Entreprise",
                name="type_client",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("telephone", sa.String(length=30), nullable=True),
        sa.Column("adresse", sa.String(length=255), nullable=True),
        sa.Column("mot_de_passe", sa.String(length=255), nullable=False),
        sa.Column(
            "date_creation_compte",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id_client", name=op.f("pk_client")),
        sa.UniqueConstraint("email", name=op.f("uq_client_email")),
    )
    op.create_table(
        "domaine_formation",
        sa.Column("id_domaine", sa.Integer(), nullable=False),
        sa.Column("libelle", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id_domaine", name=op.f("pk_domaine_formation")),
        sa.UniqueConstraint("libelle", name=op.f("uq_domaine_formation_libelle")),
    )
    op.create_table(
        "logement",
        sa.Column("id_logement", sa.Integer(), nullable=False),
        sa.Column("type_chambre", sa.String(length=50), nullable=False),
        sa.Column("capacite", sa.Integer(), nullable=False),
        sa.Column("tarif_nuitee", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("statut", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id_logement", name=op.f("pk_logement")),
    )
    op.create_table(
        "personnel",
        sa.Column("id_personnel", sa.Integer(), nullable=False),
        sa.Column("nom", sa.String(length=100), nullable=False),
        sa.Column("prenom", sa.String(length=100), nullable=False),
        sa.Column("fonction", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("telephone", sa.String(length=30), nullable=True),
        sa.Column("date_embauche", sa.Date(), nullable=True),
        sa.Column("specialite", sa.String(length=100), nullable=True),
        sa.Column("zone_livraison", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id_personnel", name=op.f("pk_personnel")),
        sa.UniqueConstraint("email", name=op.f("uq_personnel_email")),
    )
    op.create_table(
        "salle",
        sa.Column("id_salle", sa.Integer(), nullable=False),
        sa.Column("nom", sa.String(length=100), nullable=False),
        sa.Column("capacite", sa.Integer(), nullable=False),
        sa.Column("tarif_horaire", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("tarif_journee", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("equipements", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id_salle", name=op.f("pk_salle")),
    )
    op.create_table(
        "client_entreprise",
        sa.Column("id_client", sa.Integer(), nullable=False),
        sa.Column("raison_sociale", sa.String(length=200), nullable=False),
        sa.Column("numero_id_fiscal", sa.String(length=50), nullable=False),
        sa.Column("secteur_activite", sa.String(length=100), nullable=True),
        sa.Column("nom_contact_referent", sa.String(length=150), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_client"],
            ["client.id_client"],
            name=op.f("fk_client_entreprise_id_client_client"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id_client", name=op.f("pk_client_entreprise")),
        sa.UniqueConstraint(
            "numero_id_fiscal", name=op.f("uq_client_entreprise_numero_id_fiscal")
        ),
    )
    op.create_table(
        "client_particulier",
        sa.Column("id_client", sa.Integer(), nullable=False),
        sa.Column("nom", sa.String(length=100), nullable=False),
        sa.Column("prenom", sa.String(length=100), nullable=False),
        sa.Column("date_naissance", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_client"],
            ["client.id_client"],
            name=op.f("fk_client_particulier_id_client_client"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id_client", name=op.f("pk_client_particulier")),
    )
    op.create_table(
        "formation",
        sa.Column("id_formation", sa.Integer(), nullable=False),
        sa.Column("titre", sa.String(length=200), nullable=False),
        sa.Column("niveau", sa.String(length=50), nullable=True),
        sa.Column("duree_heures", sa.Integer(), nullable=False),
        sa.Column("prix", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("capacite_max", sa.Integer(), nullable=False),
        sa.Column(
            "propose_hebergement", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("id_domaine", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_domaine"],
            ["domaine_formation.id_domaine"],
            name=op.f("fk_formation_id_domaine_domaine_formation"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id_formation", name=op.f("pk_formation")),
    )
    op.create_table(
        "produit",
        sa.Column("id_produit", sa.Integer(), nullable=False),
        sa.Column("nom", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("prix_unitaire", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("unite_mesure", sa.String(length=30), nullable=False),
        sa.Column("stock_disponible", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "est_personnalisable", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("est_livrable", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id_categorie", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_categorie"],
            ["categorie_produit.id_categorie"],
            name=op.f("fk_produit_id_categorie_categorie_produit"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id_produit", name=op.f("pk_produit")),
    )
    op.create_table(
        "abonnement",
        sa.Column("id_abonnement", sa.Integer(), nullable=False),
        sa.Column("date_debut", sa.Date(), nullable=False),
        sa.Column("date_fin", sa.Date(), nullable=True),
        sa.Column(
            "type_facturation",
            sa.Enum(
                "Forfait",
                "Consommation_reelle",
                name="type_facturation",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "mode_suivi",
            sa.Enum(
                "Individuel",
                "Global",
                name="mode_suivi",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("nombre_repas_inclus", sa.Integer(), nullable=True),
        sa.Column("tarif_forfait", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "tarif_unitaire_repas", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.Column("id_client_entreprise", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_client_entreprise"],
            ["client_entreprise.id_client"],
            name=op.f("fk_abonnement_id_client_entreprise_client_entreprise"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id_abonnement", name=op.f("pk_abonnement")),
    )
    op.create_table(
        "session_formation",
        sa.Column("id_session", sa.Integer(), nullable=False),
        sa.Column("date_debut", sa.Date(), nullable=False),
        sa.Column("date_fin", sa.Date(), nullable=False),
        sa.Column("places_restantes", sa.Integer(), nullable=False),
        sa.Column("statut", sa.String(length=30), nullable=False),
        sa.Column("id_formation", sa.Integer(), nullable=False),
        sa.Column("id_formateur", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_formateur"],
            ["personnel.id_personnel"],
            name=op.f("fk_session_formation_id_formateur_personnel"),
        ),
        sa.ForeignKeyConstraint(
            ["id_formation"],
            ["formation.id_formation"],
            name=op.f("fk_session_formation_id_formation_formation"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id_session", name=op.f("pk_session_formation")),
    )
    op.create_table(
        "beneficiaire",
        sa.Column("id_beneficiaire", sa.Integer(), nullable=False),
        sa.Column("nom", sa.String(length=100), nullable=False),
        sa.Column("prenom", sa.String(length=100), nullable=False),
        sa.Column("identifiant_badge", sa.String(length=50), nullable=False),
        sa.Column("statut", sa.String(length=30), nullable=False),
        sa.Column("id_abonnement", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_abonnement"],
            ["abonnement.id_abonnement"],
            name=op.f("fk_beneficiaire_id_abonnement_abonnement"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id_beneficiaire", name=op.f("pk_beneficiaire")),
        sa.UniqueConstraint(
            "identifiant_badge", name=op.f("uq_beneficiaire_identifiant_badge")
        ),
    )
    op.create_table(
        "reservation",
        sa.Column("id_reservation", sa.Integer(), nullable=False),
        sa.Column(
            "type_reservation",
            sa.Enum(
                "Formation",
                "Salle",
                "Logement",
                "Table",
                name="type_reservation",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("date_debut", sa.DateTime(timezone=True), nullable=False),
        sa.Column("date_fin", sa.DateTime(timezone=True), nullable=False),
        sa.Column("nombre_personnes", sa.Integer(), server_default="1", nullable=False),
        sa.Column("statut", sa.String(length=30), nullable=False),
        sa.Column(
            "avec_hebergement", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("id_client", sa.Integer(), nullable=False),
        sa.Column("id_session", sa.Integer(), nullable=True),
        sa.Column("id_salle", sa.Integer(), nullable=True),
        sa.Column("id_logement", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "(id_session IS NOT NULL)::int + (id_salle IS NOT NULL)::int + (id_logement IS NOT NULL)::int <= 1",
            name=op.f("ck_reservation_cible_unique"),
        ),
        sa.ForeignKeyConstraint(
            ["id_client"],
            ["client.id_client"],
            name=op.f("fk_reservation_id_client_client"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["id_logement"],
            ["logement.id_logement"],
            name=op.f("fk_reservation_id_logement_logement"),
        ),
        sa.ForeignKeyConstraint(
            ["id_salle"], ["salle.id_salle"], name=op.f("fk_reservation_id_salle_salle")
        ),
        sa.ForeignKeyConstraint(
            ["id_session"],
            ["session_formation.id_session"],
            name=op.f("fk_reservation_id_session_session_formation"),
        ),
        sa.PrimaryKeyConstraint("id_reservation", name=op.f("pk_reservation")),
    )
    op.create_table(
        "commande",
        sa.Column("id_commande", sa.Integer(), nullable=False),
        sa.Column("nom_invite", sa.String(length=150), nullable=True),
        sa.Column("contact_invite", sa.String(length=150), nullable=True),
        sa.Column("type_commande", sa.String(length=30), nullable=False),
        sa.Column("statut", sa.String(length=30), nullable=False),
        sa.Column(
            "montant_total",
            sa.Numeric(precision=12, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column("id_client", sa.Integer(), nullable=True),
        sa.Column("id_reservation", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_client"],
            ["client.id_client"],
            name=op.f("fk_commande_id_client_client"),
        ),
        sa.ForeignKeyConstraint(
            ["id_reservation"],
            ["reservation.id_reservation"],
            name=op.f("fk_commande_id_reservation_reservation"),
        ),
        sa.PrimaryKeyConstraint("id_commande", name=op.f("pk_commande")),
    )
    op.create_table(
        "consommation_repas",
        sa.Column("id_consommation", sa.Integer(), nullable=False),
        sa.Column("date_consommation", sa.Date(), nullable=False),
        sa.Column("quantite", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id_abonnement", sa.Integer(), nullable=False),
        sa.Column("id_beneficiaire", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_abonnement"],
            ["abonnement.id_abonnement"],
            name=op.f("fk_consommation_repas_id_abonnement_abonnement"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["id_beneficiaire"],
            ["beneficiaire.id_beneficiaire"],
            name=op.f("fk_consommation_repas_id_beneficiaire_beneficiaire"),
        ),
        sa.PrimaryKeyConstraint("id_consommation", name=op.f("pk_consommation_repas")),
    )
    op.create_table(
        "ligne_commande",
        sa.Column("id_ligne", sa.Integer(), nullable=False),
        sa.Column("quantite", sa.Integer(), nullable=False),
        sa.Column(
            "prix_unitaire_applique", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column("id_commande", sa.Integer(), nullable=False),
        sa.Column("id_produit", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_commande"],
            ["commande.id_commande"],
            name=op.f("fk_ligne_commande_id_commande_commande"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["id_produit"],
            ["produit.id_produit"],
            name=op.f("fk_ligne_commande_id_produit_produit"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id_ligne", name=op.f("pk_ligne_commande")),
    )
    op.create_table(
        "livraison",
        sa.Column("id_livraison", sa.Integer(), nullable=False),
        sa.Column("adresse_livraison", sa.Text(), nullable=False),
        sa.Column("date_heure_prevue", sa.DateTime(timezone=True), nullable=False),
        sa.Column("date_heure_reelle", sa.DateTime(timezone=True), nullable=True),
        sa.Column("statut", sa.String(length=30), nullable=False),
        sa.Column("id_commande", sa.Integer(), nullable=False),
        sa.Column("id_personnel", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_commande"],
            ["commande.id_commande"],
            name=op.f("fk_livraison_id_commande_commande"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["id_personnel"],
            ["personnel.id_personnel"],
            name=op.f("fk_livraison_id_personnel_personnel"),
        ),
        sa.PrimaryKeyConstraint("id_livraison", name=op.f("pk_livraison")),
        sa.UniqueConstraint("id_commande", name=op.f("uq_livraison_id_commande")),
    )
    op.create_table(
        "avis",
        sa.Column("id_avis", sa.Integer(), nullable=False),
        sa.Column(
            "type_avis",
            sa.Enum(
                "Produit",
                "Service",
                name="type_avis",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("note", sa.Integer(), nullable=False),
        sa.Column("commentaire", sa.Text(), nullable=True),
        sa.Column(
            "date_avis",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id_client", sa.Integer(), nullable=False),
        sa.Column("id_ligne", sa.Integer(), nullable=True),
        sa.Column("id_reservation", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "(id_ligne IS NOT NULL) <> (id_reservation IS NOT NULL)",
            name=op.f("ck_avis_cible_xor"),
        ),
        sa.CheckConstraint(
            "note BETWEEN 1 AND 5", name=op.f("ck_avis_note_intervalle")
        ),
        sa.ForeignKeyConstraint(
            ["id_client"],
            ["client.id_client"],
            name=op.f("fk_avis_id_client_client"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["id_ligne"],
            ["ligne_commande.id_ligne"],
            name=op.f("fk_avis_id_ligne_ligne_commande"),
        ),
        sa.ForeignKeyConstraint(
            ["id_reservation"],
            ["reservation.id_reservation"],
            name=op.f("fk_avis_id_reservation_reservation"),
        ),
        sa.PrimaryKeyConstraint("id_avis", name=op.f("pk_avis")),
    )
    op.create_table(
        "demande_personnalisation",
        sa.Column("id_personnalisation", sa.Integer(), nullable=False),
        sa.Column("description_demande", sa.Text(), nullable=False),
        sa.Column("ingredients_specifiques", sa.Text(), nullable=True),
        sa.Column(
            "supplement_prix",
            sa.Numeric(precision=10, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column("id_ligne", sa.Integer(), nullable=False),
        sa.Column("id_produit_base", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_ligne"],
            ["ligne_commande.id_ligne"],
            name=op.f("fk_demande_personnalisation_id_ligne_ligne_commande"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["id_produit_base"],
            ["produit.id_produit"],
            name=op.f("fk_demande_personnalisation_id_produit_base_produit"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id_personnalisation", name=op.f("pk_demande_personnalisation")
        ),
        sa.UniqueConstraint(
            "id_ligne", name=op.f("uq_demande_personnalisation_id_ligne")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("demande_personnalisation")
    op.drop_table("avis")
    op.drop_table("livraison")
    op.drop_table("ligne_commande")
    op.drop_table("consommation_repas")
    op.drop_table("commande")
    op.drop_table("reservation")
    op.drop_table("beneficiaire")
    op.drop_table("session_formation")
    op.drop_table("abonnement")
    op.drop_table("produit")
    op.drop_table("formation")
    op.drop_table("client_particulier")
    op.drop_table("client_entreprise")
    op.drop_table("salle")
    op.drop_table("personnel")
    op.drop_table("logement")
    op.drop_table("domaine_formation")
    op.drop_table("client")
    op.drop_table("categorie_produit")
    # ### end Alembic commands ###
