"""domaine de fonction et est_administrateur sur personnel

Revision ID: 728322ff227b
Revises: 263bf13e295b
Create Date: 2026-08-04 16:35:15.155901

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "728322ff227b"
down_revision: str | Sequence[str] | None = "263bf13e295b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Domaine de `PERSONNEL.fonction`. Repris litteralement plutot qu'importe de
#: `app.models` : une migration decrit l'etat du schema a un instant donne, elle
#: ne doit pas changer de sens quand le modele evolue.
FONCTIONS = ("Formateur", "Livreur", "Cuisinier", "Receptionniste", "Autre")

TYPE_FONCTION = sa.Enum(
    *FONCTIONS,
    name="fonction_personnel",
    native_enum=False,
    create_constraint=True,
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "personnel",
        sa.Column(
            "est_administrateur",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # `native_enum=False` : pas de type ENUM PostgreSQL, mais un VARCHAR assorti
    # d'un CHECK. Contrairement au CHECK de `commande` (revision 2befac0654c1),
    # celui-ci n'a PAS eu besoin d'etre ajoute a la main — verifie contre la base
    # apres execution : `alter_column` emet bien
    # `ck_personnel_fonction_personnel`, et le `downgrade` le retire.
    #
    # Effet de bord a connaitre : le VARCHAR passe de 50 a 14 caracteres, la
    # longueur de la plus longue valeur du domaine. C'est un retrecissement, qui
    # echouerait sur une valeur existante plus longue. La table est vide, et
    # toute valeur future est bornee par le CHECK lui-meme.
    op.alter_column(
        "personnel",
        "fonction",
        existing_type=sa.VARCHAR(length=50),
        type_=TYPE_FONCTION,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "personnel",
        "fonction",
        existing_type=TYPE_FONCTION,
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.drop_column("personnel", "est_administrateur")
    # ### end Alembic commands ###
