"""ajoute supprime_le et les index uniques partiels

Revision ID: ce64eca5e1d3
Revises: a0513a08ec73
Create Date: 2026-07-27 18:13:56.631346

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce64eca5e1d3"
down_revision: str | Sequence[str] | None = "a0513a08ec73"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "abonnement",
        sa.Column("supprime_le", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "avis", sa.Column("supprime_le", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "beneficiaire",
        sa.Column("supprime_le", sa.DateTime(timezone=True), nullable=True),
    )
    op.drop_constraint(
        op.f("uq_beneficiaire_identifiant_badge"), "beneficiaire", type_="unique"
    )
    op.create_index(
        "uq_beneficiaire_identifiant_badge",
        "beneficiaire",
        ["identifiant_badge"],
        unique=True,
        postgresql_where=sa.text("supprime_le IS NULL"),
        sqlite_where=sa.text("supprime_le IS NULL"),
    )
    op.add_column(
        "categorie_produit",
        sa.Column("supprime_le", sa.DateTime(timezone=True), nullable=True),
    )
    op.drop_constraint(
        op.f("uq_categorie_produit_libelle"), "categorie_produit", type_="unique"
    )
    op.create_index(
        "uq_categorie_produit_libelle",
        "categorie_produit",
        ["libelle"],
        unique=True,
        postgresql_where=sa.text("supprime_le IS NULL"),
        sqlite_where=sa.text("supprime_le IS NULL"),
    )
    op.add_column(
        "client", sa.Column("supprime_le", sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_constraint(op.f("uq_client_email"), "client", type_="unique")
    op.create_index(
        "uq_client_email",
        "client",
        ["email"],
        unique=True,
        postgresql_where=sa.text("supprime_le IS NULL"),
        sqlite_where=sa.text("supprime_le IS NULL"),
    )
    op.add_column(
        "client_entreprise",
        sa.Column("supprime_le", sa.DateTime(timezone=True), nullable=True),
    )
    op.drop_constraint(
        op.f("uq_client_entreprise_numero_id_fiscal"),
        "client_entreprise",
        type_="unique",
    )
    op.create_index(
        "uq_client_entreprise_numero_id_fiscal",
        "client_entreprise",
        ["numero_id_fiscal"],
        unique=True,
        postgresql_where=sa.text("supprime_le IS NULL"),
        sqlite_where=sa.text("supprime_le IS NULL"),
    )
    op.add_column(
        "client_particulier",
        sa.Column("supprime_le", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "commande", sa.Column("supprime_le", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "consommation_repas",
        sa.Column("supprime_le", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "demande_personnalisation",
        sa.Column("supprime_le", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "domaine_formation",
        sa.Column("supprime_le", sa.DateTime(timezone=True), nullable=True),
    )
    op.drop_constraint(
        op.f("uq_domaine_formation_libelle"), "domaine_formation", type_="unique"
    )
    op.create_index(
        "uq_domaine_formation_libelle",
        "domaine_formation",
        ["libelle"],
        unique=True,
        postgresql_where=sa.text("supprime_le IS NULL"),
        sqlite_where=sa.text("supprime_le IS NULL"),
    )
    op.add_column(
        "formation", sa.Column("supprime_le", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "ligne_commande",
        sa.Column("supprime_le", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "livraison", sa.Column("supprime_le", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "logement", sa.Column("supprime_le", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "personnel", sa.Column("supprime_le", sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_constraint(op.f("uq_personnel_email"), "personnel", type_="unique")
    op.create_index(
        "uq_personnel_email",
        "personnel",
        ["email"],
        unique=True,
        postgresql_where=sa.text("supprime_le IS NULL"),
        sqlite_where=sa.text("supprime_le IS NULL"),
    )
    op.add_column(
        "produit", sa.Column("supprime_le", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "reservation",
        sa.Column("supprime_le", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "salle", sa.Column("supprime_le", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "session_formation",
        sa.Column("supprime_le", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("session_formation", "supprime_le")
    op.drop_column("salle", "supprime_le")
    op.drop_column("reservation", "supprime_le")
    op.drop_column("produit", "supprime_le")
    op.drop_index(
        "uq_personnel_email",
        table_name="personnel",
        postgresql_where=sa.text("supprime_le IS NULL"),
        sqlite_where=sa.text("supprime_le IS NULL"),
    )
    op.create_unique_constraint(
        op.f("uq_personnel_email"),
        "personnel",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("personnel", "supprime_le")
    op.drop_column("logement", "supprime_le")
    op.drop_column("livraison", "supprime_le")
    op.drop_column("ligne_commande", "supprime_le")
    op.drop_column("formation", "supprime_le")
    op.drop_index(
        "uq_domaine_formation_libelle",
        table_name="domaine_formation",
        postgresql_where=sa.text("supprime_le IS NULL"),
        sqlite_where=sa.text("supprime_le IS NULL"),
    )
    op.create_unique_constraint(
        op.f("uq_domaine_formation_libelle"),
        "domaine_formation",
        ["libelle"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("domaine_formation", "supprime_le")
    op.drop_column("demande_personnalisation", "supprime_le")
    op.drop_column("consommation_repas", "supprime_le")
    op.drop_column("commande", "supprime_le")
    op.drop_column("client_particulier", "supprime_le")
    op.drop_index(
        "uq_client_entreprise_numero_id_fiscal",
        table_name="client_entreprise",
        postgresql_where=sa.text("supprime_le IS NULL"),
        sqlite_where=sa.text("supprime_le IS NULL"),
    )
    op.create_unique_constraint(
        op.f("uq_client_entreprise_numero_id_fiscal"),
        "client_entreprise",
        ["numero_id_fiscal"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("client_entreprise", "supprime_le")
    op.drop_index(
        "uq_client_email",
        table_name="client",
        postgresql_where=sa.text("supprime_le IS NULL"),
        sqlite_where=sa.text("supprime_le IS NULL"),
    )
    op.create_unique_constraint(
        op.f("uq_client_email"),
        "client",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("client", "supprime_le")
    op.drop_index(
        "uq_categorie_produit_libelle",
        table_name="categorie_produit",
        postgresql_where=sa.text("supprime_le IS NULL"),
        sqlite_where=sa.text("supprime_le IS NULL"),
    )
    op.create_unique_constraint(
        op.f("uq_categorie_produit_libelle"),
        "categorie_produit",
        ["libelle"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("categorie_produit", "supprime_le")
    op.drop_index(
        "uq_beneficiaire_identifiant_badge",
        table_name="beneficiaire",
        postgresql_where=sa.text("supprime_le IS NULL"),
        sqlite_where=sa.text("supprime_le IS NULL"),
    )
    op.create_unique_constraint(
        op.f("uq_beneficiaire_identifiant_badge"),
        "beneficiaire",
        ["identifiant_badge"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("beneficiaire", "supprime_le")
    op.drop_column("avis", "supprime_le")
    op.drop_column("abonnement", "supprime_le")
    # ### end Alembic commands ###
