"""ajoute les domaines de type_commande et statut

Revision ID: 9e110ea805b4
Revises: ce64eca5e1d3
Create Date: 2026-07-28 10:46:25.624339

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e110ea805b4"
down_revision: str | Sequence[str] | None = "ce64eca5e1d3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "commande",
        "type_commande",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.Enum(
            "En_ligne",
            "Sur_place",
            "A_emporter",
            name="type_commande",
            native_enum=False,
            create_constraint=True,
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "commande",
        "statut",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.Enum(
            "En_attente",
            "Confirmee",
            "En_preparation",
            "Livree",
            "Servie",
            "Annulee",
            name="statut_commande",
            native_enum=False,
            create_constraint=True,
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "commande",
        "statut",
        existing_type=sa.Enum(
            "En_attente",
            "Confirmee",
            "En_preparation",
            "Livree",
            "Servie",
            "Annulee",
            name="statut_commande",
            native_enum=False,
            create_constraint=True,
        ),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    op.alter_column(
        "commande",
        "type_commande",
        existing_type=sa.Enum(
            "En_ligne",
            "Sur_place",
            "A_emporter",
            name="type_commande",
            native_enum=False,
            create_constraint=True,
        ),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
